<?php 
/*
Plugin Name: cost
Plugin URI: https://lovetoreads.com
Description: ddd
Version: 0.1
Author: sh
Author URI: https://lovetoreads.com
Text Domain: c
Generated By: http://ensuredomains.com
*/

// If this file is called directly, abort. //
if ( ! defined( 'WPINC' ) ) {die;} // end if

// Let's Initialize Everything
if ( file_exists( plugin_dir_path( __FILE__ ) . 'core-init.php' ) ) {
require_once( plugin_dir_path( __FILE__ ) . 'core-init.php' );
}